version: '2'
services:
  webserver:
    image: vemcompy/python_webserver:v1.0
    environment:
      WEBSERVICE_PORT: '8080'
      WEBSERVICE_NAME: 'WEB_SERVICE_RAFAEL'
      WEBSERVICE_VERSION: 'v1.0'	